/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/
        
/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.example;

import org.junit.Test;
import org.mule.api.MuleEvent;
import org.mule.tck.junit4.FunctionalTestCase;

import java.util.Map;

import static junit.framework.Assert.assertEquals;

public class ExampleDynamicMetadataConnectorTest extends FunctionalTestCase
{
    @Override
    protected String getConfigFile()
    {
        return "mule-config.xml";
    }

    @Test
    public void testFlow() throws Exception
    {
        MuleEvent event = runFlow("testFlow", null);
        assertEquals(((Map) event.getMessage().getPayload()).get("name"),"testAuthorName");
        assertEquals(((Map) event.getMessage().getPayload()).get("lastName"),"testAuthorLastName");
    }
}
