/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/
        
/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.example;

import org.junit.Test;
import org.mule.docs.example.model.Author;
import org.mule.tck.junit4.FunctionalTestCase;

import static org.junit.Assert.fail;

public class ExampleConnectorTest extends FunctionalTestCase
{
    @Override
    protected String getConfigFile()
    {
        return "mule-config.xml";
    }

    @Test(expected = Exception.class)
    public void testFlow() throws Exception {
        runFlow("queryTestFlow", new Author());
        fail("An exception was expected to be thrown");
    }
}
